resume_analysis:
  model: "openai/gpt-4"
  temperature: 0.7
  max_tokens: 1000

resume_generation:
  output_dir: "./data/generated"
  formats: ["pdf", "docx"]

cover_letter:
  default_style: "professional"